# Generated by Django 4.1 on 2022-08-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Skill')),
                ('level', models.CharField(max_length=30, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='LatestWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTilte', models.CharField(max_length=30, verbose_name='Work Tilte ')),
                ('description', models.TextField(verbose_name='Description')),
                ('linkRedirect', models.CharField(default='#', max_length=100, verbose_name='Work Tilte ')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Skill')),
                ('level', models.CharField(max_length=30, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('birth', models.IntegerField(verbose_name='Data de Nascimento')),
                ('linkedin', models.CharField(max_length=50, verbose_name='Likedin')),
                ('gitHub', models.CharField(max_length=50, verbose_name='GitHub')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeRange', models.CharField(max_length=30, verbose_name='Time')),
                ('officename', models.CharField(max_length=30, verbose_name='Office Name')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceComplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemtText', models.TextField(verbose_name='Complement')),
                ('idWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.workexperience')),
            ],
        ),
    ]
