# Generated by Django 4.1 on 2022-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=30, verbose_name='salutation')),
                ('textSalutation', models.CharField(max_length=100, verbose_name='Text Salutation')),
                ('aboutMe', models.TextField(verbose_name='About Me')),
            ],
        ),
    ]
