# Generated by Django 4.1 on 2022-08-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestworks',
            name='linkRedirect',
        ),
    ]
