# Generated by Django 4.1 on 2022-08-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_latestworks_linkredirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tile')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Subtile')),
                ('year', models.CharField(max_length=30, verbose_name='Time')),
                ('description', models.TextField(verbose_name='Description')),
                ('idWK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.latestworks')),
            ],
        ),
    ]
