# Generated by Django 4.1 on 2022-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Subtile'),
        ),
        migrations.AlterField(
            model_name='details',
            name='year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
