# Generated by Django 4.1 on 2022-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_details_subtitle_alter_details_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='year',
            field=models.DateField(auto_now=True),
        ),
    ]
