# Generated by Django 4.1 on 2022-09-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tools_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTilte', models.CharField(max_length=30, verbose_name='Work Tilte ')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tile')),
                ('subtitle', models.CharField(blank=True, max_length=30, verbose_name='Subtile')),
                ('year', models.DateField(auto_now=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('idWK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
            ],
        ),
    ]
