# Generated by Django 4.1 on 2022-09-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articles_detailsarticles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsarticles',
            old_name='idWK',
            new_name='idArt',
        ),
        migrations.AlterField(
            model_name='articles',
            name='articleTilte',
            field=models.CharField(max_length=30, verbose_name='Article Tilte'),
        ),
    ]
