# Generated by Django 4.1 on 2022-09-13 08:40

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_idwk_detailsarticles_idart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=stdimage.models.StdImageField(default=False, force_min_size=False, upload_to='articles', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='isRedirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='latestworks',
            name='isRedirect',
            field=models.BooleanField(default=False),
        ),
    ]
